# CUDA_VISIBLE_DEVICES=2 python flowertune-eval-medical/eval.py --base-model-name-path "HuggingFaceTB/SmolLM2-135M" --peft-path="./results/SmolLM2-135M/peft_200/" --run-name="eval_results_SmolLM2-135M"  --batch-size=16 --quantization=4 --datasets="pubmedqa"
# CUDA_VISIBLE_DEVICES=2 python flowertune-eval-medical/eval.py --base-model-name-path "HuggingFaceTB/SmolLM2-135M" --peft-path="./results/SmolLM2-135M/peft_200/" --run-name="eval_results_SmolLM2-135M"  --batch-size=16 --quantization=4 --datasets="medqa"
# CUDA_VISIBLE_DEVICES=2 python flowertune-eval-medical/eval.py --base-model-name-path "HuggingFaceTB/SmolLM2-135M" --peft-path="./results/SmolLM2-135M/peft_200/" --run-name="eval_results_SmolLM2-135M"  --batch-size=16 --quantization=4 --datasets="medmcqa"
# CUDA_VISIBLE_DEVICES=2 python flowertune-eval-medical/eval.py --base-model-name-path "HuggingFaceTB/SmolLM2-135M" --peft-path="./results/SmolLM2-135M/peft_200/" --run-name="eval_results_SmolLM2-135M"  --batch-size=16 --quantization=4 --datasets="careqa"

CUDA_VISIBLE_DEVICES=2 python flowertune-eval-medical/eval.py --base-model-name-path "HuggingFaceTB/SmolLM2-135M-Instruct" --peft-path="./results/SmolLM2-135M-Instruct/peft_200/" --run-name="eval_results_SmolLM2-135M-Instruct"  --batch-size=16 --quantization=4 --datasets="pubmedqa"
CUDA_VISIBLE_DEVICES=2 python flowertune-eval-medical/eval.py --base-model-name-path "HuggingFaceTB/SmolLM2-135M-Instruct" --peft-path="./results/SmolLM2-135M-Instruct/peft_200/" --run-name="eval_results_SmolLM2-135M-Instruct"  --batch-size=16 --quantization=4 --datasets="medqa"
CUDA_VISIBLE_DEVICES=2 python flowertune-eval-medical/eval.py --base-model-name-path "HuggingFaceTB/SmolLM2-135M-Instruct" --peft-path="./results/SmolLM2-135M-Instruct/peft_200/" --run-name="eval_results_SmolLM2-135M-Instruct"  --batch-size=16 --quantization=4 --datasets="medmcqa"
CUDA_VISIBLE_DEVICES=2 python flowertune-eval-medical/eval.py --base-model-name-path "HuggingFaceTB/SmolLM2-135M-Instruct" --peft-path="./results/SmolLM2-135M-Instruct/peft_200/" --run-name="eval_results_SmolLM2-135M-Instruct"  --batch-size=16 --quantization=4 --datasets="careqa"

# CUDA_VISIBLE_DEVICES=2 python flowertune-eval-medical/eval.py --base-model-name-path "HuggingFaceTB/SmolLM2-360M-Instruct" --peft-path="./results/SmolLM2-360M-Instruct/peft_200/" --run-name="eval_results_SmolLM2-360M-Instruct"  --batch-size=16 --quantization=4 --datasets="pubmedqa"
# CUDA_VISIBLE_DEVICES=2 python flowertune-eval-medical/eval.py --base-model-name-path "HuggingFaceTB/SmolLM2-360M-Instruct" --peft-path="./results/SmolLM2-360M-Instruct/peft_200/" --run-name="eval_results_SmolLM2-360M-Instruct"  --batch-size=16 --quantization=4 --datasets="medqa"
# CUDA_VISIBLE_DEVICES=2 python flowertune-eval-medical/eval.py --base-model-name-path "HuggingFaceTB/SmolLM2-360M-Instruct" --peft-path="./results/SmolLM2-360M-Instruct/peft_200/" --run-name="eval_results_SmolLM2-360M-Instruct"  --batch-size=16 --quantization=4 --datasets="medmcqa"
# CUDA_VISIBLE_DEVICES=2 python flowertune-eval-medical/eval.py --base-model-name-path "HuggingFaceTB/SmolLM2-360M-Instruct" --peft-path="./results/SmolLM2-360M-Instruct/peft_200/" --run-name="eval_results_SmolLM2-360M-Instruct"  --batch-size=16 --quantization=4 --datasets="careqa"

# CUDA_VISIBLE_DEVICES=2 python flowertune-eval-medical/eval.py --base-model-name-path "HuggingFaceTB/SmolLM2-360M" --peft-path="./results/SmolLM2-360M/peft_200/" --run-name="eval_results_SmolLM2-360M"  --batch-size=16 --quantization=4 --datasets="pubmedqa"
# CUDA_VISIBLE_DEVICES=2 python flowertune-eval-medical/eval.py --base-model-name-path "HuggingFaceTB/SmolLM2-360M" --peft-path="./results/SmolLM2-360M/peft_200/" --run-name="eval_results_SmolLM2-360M"  --batch-size=16 --quantization=4 --datasets="medqa"
# CUDA_VISIBLE_DEVICES=2 python flowertune-eval-medical/eval.py --base-model-name-path "HuggingFaceTB/SmolLM2-360M" --peft-path="./results/SmolLM2-360M/peft_200/" --run-name="eval_results_SmolLM2-360M"  --batch-size=16 --quantization=4 --datasets="medmcqa"
# CUDA_VISIBLE_DEVICES=2 python flowertune-eval-medical/eval.py --base-model-name-path "HuggingFaceTB/SmolLM2-360M" --peft-path="./results/SmolLM2-360M/peft_200/" --run-name="eval_results_SmolLM2-360M"  --batch-size=16 --quantization=4 --datasets="careqa"
